# TLS gateway certificate
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.ingressGateway.tlsCertificate.name }}
  {{- if .Values.rootNamespace }}
  namespace: {{ .Values.rootNamespace }}
  {{- end }}
  labels:
  {{- include "mesh.labels" . | nindent 4 }}
spec:
  dnsNames: {{ toYaml .Values.ingressGateway.tlsCertificate.dnsNames | nindent 4 }}
  issuerRef:
    {{- toYaml .Values.ingressGateway.tlsCertificate.issuerRef | nindent 4 }}
  privateKey:
    {{- toYaml .Values.ingressGateway.tlsCertificate.privateKey | nindent 4 }}
  renewBefore: {{ .Values.ingressGateway.tlsCertificate.renewBefore }}
  {{- if .Values.ingressGateway.tlsCertificate.secretName }}
  secretName: {{ .Values.ingressGateway.tlsCertificate.secretName }}
  {{- else }}
  secretName: {{ .Values.ingressGateway.tlsCertificate.name }}
  {{- end }}
